name: Say hello

on:
    push:
        branches:
        - main

jobs:
    hello_world:
        runs-on: ubuntu-22.04
        steps:
            -   name: Echo the message
                run: echo "Hola raul!"
            -   name: La hora
                run: date
            -   name: Directorio
                run: ls -l